# Generated by Django 3.2.6 on 2021-09-22 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='children',
            field=models.IntegerField(choices=[(1, '湖北省'), (2, '湖南省'), (3, '广东省'), (4, '安徽省'), (5, '四川省'), (6, '宁夏回族自治区')], verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='family',
            name='husband',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='husbands',
            name='name',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='项目名称'),
        ),
    ]
